version: "3.4"

services:
  my-nginx-service:
      image: nginx
      ports:
        - 8000:80
      networks:
        - nginx
        - loki-net
      environment:
        - FOO=bar
      logging:
        driver: loki
        options:
          loki-url: http://127.0.0.1:3100/loki/api/v1/push
          loki-external-labels: job=dockerlogs,owner=ryan,environment=development

networks:
  nginx:
  loki-net:
    external:
      name: loki-net