version: "3.4"

services:
  my-nginx-service:
      image: nginx
      ports:
        - 8001:80
      environment:
        - FOO=bar
      logging:
        driver: loki
        options:
          loki-url: http://127.0.0.1:3100/loki/api/v1/push
          loki-external-labels: job=nginx,environment=development
